import pandas as pd


class ClassicalSequenceLearner:
    def __init__(self): ...

    def fit(self, y: pd.Series): ...

    def predict(self) -> pd.Series: ...


class NeuralSequenceLearner:

    def __init__(self): ...

    def fit(self, y: pd.Series): ...

    def predict(self) -> pd.Series: ...
